### ISSUE TITLE
[BUG] 'WhatsApp' object has no attribute 'instance'

### ISSUE THREAD

**Issue by pptx704** [filipporomani/whatsapp-python#24]
**Describe the bug**
For most of the operations, I get the following errors-

```python
    changed_field = self.instance.changed_field(data)
                    ^^^^^^^^^^^^^
AttributeError: 'WhatsApp' object has no attribute 'instance'
```

**To Reproduce**
```python
from whatsapp import WhatsApp

token = os.environ.get("WHATSAPP_TOKEN")
phone_number_id = os.environ.get("PHONE_ID")
app = WhatsApp(token, phone_number_id)

@app.on_message
async def on_message(message):
    question = message.content
    await message.reply(message.content)

app.run("0.0.0.0", 5000)
```

**Expected behavior**
Should echo the same message as a response.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 22.04
 - Python: 3.11
 - Environment Manager: Poetry

**Additional context**
Removing `.instance` from all `self.instance` fixes this. Not sure if that's the valid fix. Maybe add test cases?

**Comment by filipporomani** [comment]
Hello! Thanks for reporting the issue, and sorry for the inconvenience. I'll work on this asap.

**Comment by Wingrammer** [comment]
Hello,
Am afraid that did not fix the issue as it added the attribute instance to the Message class and bot the Whatsapp class. You'd still have that bug if you called the send_location method.

**Comment by Wingrammer** [comment]
`def send_location(self, lat: str, long: str, name: str, address: str, recipient_id: str, sender = None) -> dict:
    """
    Sends a location message to a WhatsApp user

    Args:
        lat[str]: Latitude of the location
        long[str]: Longitude of the location
        name[str]: Name of the location
        address[str]: Address of the location
        recipient_id[str]: Phone number of the user with country code wihout +

    Example:
        >>> from whatsapp import WhatsApp
        >>> whatsapp = WhatsApp(token, phone_number_id)
        >>> whatsapp.send_location("-23.564", "-46.654", "My Location", "Rua dois, 123", "5511999999999")
    """
    try:
        sender = dict(self.l)[sender]
        
        

    except:
        sender = self.phone_number_id
        
    if sender == None:
        sender = self.phone_number_id`

I think this might be the correct beginning of the send_location method. I self.instance just became self as the 'Whatsapp' object has not attribute 'instance

**Comment by filipporomani** [comment]
That's definetly right. Missed that one in tests. I'm sorry for the inconvenience and thanks for reporting!
