### ISSUE TITLE
'WhatsApp' object has no attribute 'send_button'

### ISSUE THREAD

**Issue by deexno** [filipporomani/whatsapp-python#32]
**Describe the bug**
If I run the following example:

https://github.com/filipporomani/whatsapp/blob/main/examples/sending_button.py

I get the error: 
```
Exception has occurred: AttributeError
'WhatsApp' object has no attribute 'send_button'

File "...\whatsapp_button.py", line 17, in <module>
    response = messenger.send_button(
AttributeError: 'WhatsApp' object has no attribute 'send_button'
```

(Sending normal text messages works)

**To Reproduce**
Run it under Python 3.10. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python Version 3.10.5

**Comment by filipporomani** [comment]
That's pretty strange, as the send_button function is included in the WhatsApp class. 
I'll give a deeper look today. 
Can you also try using the version available here on GH? 
Try to install the library using git clone as shown in the installation instructions, let me know if something changes!

**Comment by filipporomani** [comment]
Hello. 
Can you please try to update the library to the latest version (3.1.0)? 
`pip install whatsapp-python --upgrade` 

The error cannot be reproduced on my machines in any OS. 
Thank you for your time!

**Comment by filipporomani** [comment]
Can't repro.
