### ISSUE TITLE
[OTHER] Removal of unicorn dependency

### ISSUE THREAD

**Issue by stanislavulrych** [filipporomani/whatsapp-python#34]
The unicorn dependency in https://github.com/filipporomani/whatsapp-python/blob/7a54595adca59f412d500c35ff697677d4b02c72/pyproject.toml#L24 seems to be abundant. I could not find any usage of it in the code. Is there any reason for this dependency to be there? Thank you in advance.

**Comment by filipporomani** [comment]
Thank you. It was a typo, the required library is `uvicorn` which is needed for the async events.
