### ISSUE TITLE
[FEAT] Multiple WhatsApp Numbers in one WhatsApp instance

### ISSUE THREAD

**Issue by stanislavulrych** [filipporomani/whatsapp-python#39]
**Is your feature request related to a problem? Please describe.**
There is a possibility to have multiple numberrs added under one WhatsApp Account. Those numbers must have a single webhook endoint. However, for sending a message from those numbers, those have different WhatsApp Number Ids.  Since the WhatsApp Number Id is specified as `phone_number_id` to `WhatsApp` class, it seems it is not possible to work with multiple WhatsApp numbers currently.

**Describe the solution you'd like**
There should be an option to provide multiple WhatsApp Number Ids, so that messages can be received (and answered) from a single `WhatsApp` instance. From the structure of the API, it seems it is only a matter of having multiple whatsapp phone number ids configurable for `WhatsApp` as all the numbers are managed under same account and whatsapp api token.

**Describe alternatives you've considered**
The alternative is to have instance of `WhatsApp` per each WhatsApp number. However, since WhatsApp platform enable having multiple numbers, it would be good to match that functionality in the `whatsapp-python` library. 

**Additional context**
Can you please advice whether the asumptions are correct?

Thank you.

**Comment by stanislavulrych** [comment]
Hi @filipporomani thank you.

Yes, I think the best solution is as you write. Furthermore keeping int as an option would only be done for backwards compabilitity, so should be marked as deprecated so it can be removed in distant future releases. All users of the library should move to the dictionary option.

Apart from that, I have no other comments!

Thanks!

Stanislav

**Comment by filipporomani** [comment]
This was partially implemented in v3.3.5.dev0.
I still need to work on sending stickers, contacts etc. but it's already implemented for sending messages.

**Comment by filipporomani** [comment]
Also, as this is a dev release, to use the new feature you need to install the last dev version:
`pip install whatsapp-python==3.3.5.dev0`

**Comment by filipporomani** [comment]
v3.3.9 released, marking this as completed.

Feel free to reopen this issue if you have anything else to ask!

Thanks again for the suggestion 💯
