### ISSUE TITLE
[BUG] in version in initialization error 

### ISSUE THREAD

**Issue by MatiusRock1** [filipporomani/whatsapp-python#41]
**Describe the bug**
in initilization conector this error  invalid literal for int() with base 10: '339post1', the error is in the version check, I opted to perform a fork and comment from line 35 to 60 of the __init_ file.

**To Reproduce**
1. initialize sdk using latest version

**Comment by filipporomani** [comment]
This is now fixed. I'm releaseing 3.3.9.post2, 5 minutes and everything should be alright!

**Comment by filipporomani** [comment]
https://pypi.org/project/whatsapp-python/3.3.9.post2/

**Comment by filipporomani** [comment]
Thanks a lot for reporting the issue!

**Comment by MatiusRock1** [comment]
I understand the solution, but in the projects that I have deployed you force me to re-deploy, I think a better solution would be to release a version without letters.

**Comment by filipporomani** [comment]
You can also disable the automatic update checker till the next version. When initializing the WhatsApp instance, pass the update_check argument:
`app = whatsapp.WhatsApp(....., update_check=False)`

This should fix your issue also in previous versions.

**Comment by filipporomani** [comment]
Anyways, I'm uploading version 3.3.95 right now.
