### ISSUE TITLE
[BUG] Unknown path components: /<my_phone_number_id>/messages

### ISSUE THREAD

**Issue by Wingrammer** [filipporomani/whatsapp-python#46]
**Describe the bug**
Hello,
Please am getting this error when trying to send messages
Response: {'error': {'message': 'Unknown path components: /<my_phone_number_id>/messages', 'type': 'OAuthException', 'code': 2500, 'fbtrace_id': 'A2qpwyl6QGsp2ijIZSv8ZTW'}}

**To Reproduce**
1. Try to send a message by calling the send_reply_button function for example
2. See error

**Expected behavior**
Message should have been sent to recipient

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Version 22.04

**Additional context**
This is happening with 4.0.0 you just released. I had to upgrade because there was a connection timeout error with the provious version.
A little research on google suggested it was the url but when I looked at the code I could not quite find something wrong with it.

Please help

**Comment by filipporomani** [comment]
Hello! 
I just fixed this, an am releasing a new version to make everything working again. Sorry for the issue!

**Comment by filipporomani** [comment]
You can upgrade the library to version `4.0.0.post1` and every issue should be fixed. Please let me know asap if you find anything else!! 
Thanks a lot!

**Comment by Wingrammer** [comment]
My pleasure. We've got a new error.
Error:     url = f"https://graph.facebook.com/{self.instance.LATEST}/{sender}/messages"
AttributeError: 'WhatsApp' object has no attribute 'instance'

The self.instance error keeps popping up

**Comment by filipporomani** [comment]
My bad. I'm sorry for that, I keep adding instance where it shouldn't be - I'm fixing this rn

**Comment by Wingrammer** [comment]
Thank you so much, it's back working. You know I wish there were tests run before merges. If you define the roadmap and guidelines I can help out on that.
