### ISSUE TITLE
[FEAT] Can we have async version of the library? That utilizes httpx or just so that functions can be awaited

### ISSUE THREAD

**Issue by Omigirl** [filipporomani/whatsapp-python#55]
**Is your feature request related to a problem? Please describe.**
Systems I am now working with are mainly asynchronous, but this library is synchronous so I avoid using it on my async projects. 
However, I love using this library it is so much more convenient

**Describe the solution you'd like**
Option to create Async class. Like `from whatsapp import AsyncWhatsApp`

**Comment by filipporomani** [comment]
Hello! 
Thanks for your suggestion. I'll implement the async functionalities ASAP.
