### ISSUE TITLE
[OTHER] Better documentation on async (asyncio) full usage

### ISSUE THREAD

**Issue by nutax** [filipporomani/whatsapp-python#58]
It would be nice to see a full example recv/send of the async version. Maybe we miss something important. Its always good to have a complete working example.

**Comment by filipporomani** [comment]
Thank you for the suggestion!
I updated the wiki page and am going to add a few examples in the dedicated folder.

**Comment by filipporomani** [comment]
I won't add examples for every function as no significant changes are made, you only need to import asyncio and run the app in an async loop as written in the wiki.
I've written example files for send_button and send_message

**Comment by filipporomani** [comment]
To receive message nothing changes actually! As the client is handled by an async FastAPI application, no changes were made to it.
